# Numpy

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a = [1,'hello',3.5]

In [8]:
np.array(a)

array(['1', 'hello', '3.5'], dtype='<U32')

In [9]:
l = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr_gen = np.arange(1,11,2)

In [13]:
arr_gen

array([1, 3, 5, 7, 9])

In [14]:
arr_zero = np.zeros(6)
arr_zero

array([0., 0., 0., 0., 0., 0.])

In [15]:
arr_zero = np.zeros((4,8))
arr_zero

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [18]:
arr = np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Random Generation function

In [24]:
np.random.rand(10)

array([0.36694184, 0.29973076, 0.96200262, 0.81410207, 0.73144892,
       0.53289806, 0.49166197, 0.13169749, 0.49732373, 0.98545414])

In [25]:
np.random.randn(10)

array([ 2.14693139, -1.51175349, -0.71551088,  0.03177223, -0.3467291 ,
        0.65560346, -1.0228463 , -1.10361962, -0.64777894,  0.5803173 ])

In [29]:
np.random.randint(10,20,10)

array([14, 13, 10, 18, 11, 15, 18, 11, 16, 13], dtype=int32)

# Array Attributes

In [31]:
new_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
new_arr.shape

(3, 3)

In [33]:
new_arr.size

9

In [34]:
arr.dtype

dtype('float64')

Array Methods

In [35]:
arr.min()

np.float64(0.0)

In [36]:
arr.max()

np.float64(1.0)

In [37]:
arr.sum()

np.float64(50.0)

In [38]:
new_arr.sum()

np.int64(45)

In [39]:
np.sum(new_arr)

np.int64(45)

In [40]:
np.sum(new_arr, axis=0)

array([12, 15, 18])

In [41]:
np.sum(new_arr,axis=1)

array([ 6, 15, 24])

In [42]:
arr.mean()

np.float64(0.5)

In [43]:
new_arr.mean()

np.float64(5.0)

In [44]:
new_arr.std()

np.float64(2.581988897471611)

In [45]:
new_arr.argmax()

np.int64(8)

In [47]:
new_arr.argmin()

np.int64(0)

In [49]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
arr = arr.reshape(6, 5)

In [53]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])