# Arrya Operations

#### Arithmetic Operations

In [2]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [4]:
arr2 = a1 + a2
arr2

array([ 7,  9, 11, 13, 15])

In [5]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [6]:
a1//a2

array([0, 0, 0, 0, 0])

In [7]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

#### Broadcasting

In [8]:
l = [10,20,30,40]
arr = np.array(l)

In [9]:
for i in l:
    print(i + 10)

20
30
40
50


In [10]:
arr + 10

array([20, 30, 40, 50])

In [12]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [16]:
arr2 * 5

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100],
       [105, 110, 115, 120, 125]])

#### Deep & Shallow Copy

In [22]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [25]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
a[4:6] * 10
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
a 
b = a

In [28]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
a 
b = a.copy()

In [32]:
b[0]=5
b

array([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### Matrix Operations

In [41]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])

In [42]:
mat1

array([[1, 2],
       [3, 4]])

In [43]:
mat2

array([[5, 6],
       [7, 8]])

In [44]:
mat1*mat2

array([[ 5, 12],
       [21, 32]])

In [45]:
mat1 @ mat2

array([[19, 22],
       [43, 50]])

In [46]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [47]:
mat1

array([[1, 2],
       [3, 4]])

In [48]:
mat1.T

array([[1, 3],
       [2, 4]])

#### Advance array manuplation

##### Stacking Array

In [3]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [5]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

##### Splitting array

In [11]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
g = np.hsplit(c,4)

In [20]:
p = np.vsplit(c, 4)

In [21]:
for i in p:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


In [25]:
for i in g:
    print(i)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1]
 [ 5]
 [ 9]
 [13]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[ 3]
 [ 7]
 [11]
 [15]]
